name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [ 17, 21 ]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean install
      
    - name: Run tests
      run: mvn test
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sparky-lib-jdk${{ matrix.java-version }}
        path: |
          sparky-core/target/*.jar
          sparky-events/target/*.jar
          sparky-scheduler/target/*.jar
          sparky-datastore/target/*.jar
          sparky-particles/target/*.jar
          sparky-ecs/target/*.jar
          sparky-rpc/target/*.jar
          sparky-adapters/sparky-bukkit/target/*.jar
          sparky-adapters/sparky-libgdx/target/*.jar